name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: Build
      run: cargo build --verbose
      working-directory: /home/runner/work/rust-hello-world/rust-hello-world/hello_github_actions
    - name: Run tests
      run: cargo test --verbose
      working-directory: /home/runner/work/rust-hello-world/rust-hello-world/hello_github_actions
    - name: run
      run: cargo run
      working-directory: /home/runner/work/rust-hello-world/rust-hello-world/hello_github_actions
