name: Triggers runnning

on: 
  push:
    branches: 
      - "aprendiendo-**" 
  pull_request:
    branches: 
      - "aprendiendo-**" 
  issue_comment:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: Determine relative path
      run: echo "Relative path $GITHUB_WORKSPACE"
    - name: Build
      run: cargo build --verbose
      working-directory: /home/runner/work/rust-hello-world/rust-hello-world/hello_github_actions
    
  test:
    name: Testing by comment
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: Run tests
      run: cargo test --verbose
      working-directory: /home/runner/work/rust-hello-world/rust-hello-world/hello_github_actions
  
  run_comment:
    needs: [build, test]
    name: Run by coment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: run
      run: cargo run
      working-directory: /home/runner/work/rust-hello-world/rust-hello-world/hello_github_actions
