name: Triggers runnning

on: 
  push:
    branches: 
      - "aprendiendo-**" 
  pull_request:
    branches: 
      - "aprendiendo-**" 
  issue_comment:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        profile: minimal
        rust-version: 1.56.0
    - name: Determine relative path
      run: echo "Relative path $GITHUB_WORKSPACE"
    - name: Build
      run: cargo build --verbose
      working-directory: $GITHUB_WORKSPACE/rust-hello-world/hello_github_actions
    - name: Run tests
      run: cargo test --verbose
      working-directory: $GITHUB_WORKSPACE/rust-hello-world/hello_github_actions
    - name: run
      run: cargo run
      working-directory: $GITHUB_WORKSPACE/rust-hello-world/hello_github_actions

  check-comment:
    name: Check comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          profile: minimal
          rust-version: 1.56.0
    - name: Determine relative path
      run: echo "Relative path $GITHUB_WORKSPACE"
    - name: Build
      run: cargo build --verbose
      working-directory: $GITHUB_WORKSPACE/rust-hello-world/hello_github_actions
    - name: Run tests
      run: cargo test --verbose
      working-directory: $GITHUB_WORKSPACE/rust-hello-world/hello_github_actions
    - name: run
      run: cargo run
      working-directory: $GITHUB_WORKSPACE/rust-hello-world/hello_github_actions