name: Learning variables
run-name: Learning to user ariables

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - aprendiendo-github-actions

env:
  TESTING: true

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      JOB: build
    name: building
    steps:
      - name: Running on branch
        run: echo "Running on branch ${{ github.ref_name }}"
      - name: Showing step
        env: 
          STEP: 1
        run: echo "Showing variables $STEP"
      - name: Showing testing
        run: echo "Showing variables $TESTING"
      - name: Showing job
        run: echo "Showing variables $JOB"
      - name: Showing secret name
        run: echo "Showing variables ${{ secrets.SECRET_NAME }}"
      - name: Showing version
        run: echo "Showing variables ${{ env.VAR_VER }} "
